### ISSUE TITLE
More clients

### ISSUE THREAD

**Issue by KaKi87** [fstanis/awesome-webdav#6]
Hello,

MiXplorer on Android (proprietary but free) and CrossFTP Pro on all desktop platforms (proprietary and premium) support WebDAV.

Is there any free alternative to FileZilla Pro and CrossFTP Pro ?

I don't understand why WebDAV is a pro thing.

Thanks

**Comment by fstanis** [comment]
Added all three in https://github.com/fstanis/awesome-webdav/commit/bfbe535d69ab0087dc2125bb19cf6ac5a15481f6.

> Is there any free alternative to FileZilla Pro and CrossFTP Pro ?

Have you checked [the client guides](https://github.com/fstanis/awesome-webdav#client-guides)? I found it easiest to simply mount WebDAV on a system level and most OSes should support it.

**Comment by KaKi87** [comment]
> I found it easiest to simply mount WebDAV on a system level

Yes, but sessions aren't remembered and some users (like me) prefer "commander" interfaces.
